const express = require('express');
const Comment = require('../models/Comment');
const Task = require('../models/Task');
const { protect } = require('../middleware/auth');
const { logActivity } = require('../utils/activityLogger');

const router = express.Router();
router.use(protect);

// Get comments for a task
router.get('/task/:taskId', async (req, res) => {
    try {
        const comments = await Comment.find({ task: req.params.taskId })
            .populate('user', 'name username avatar role')
            .sort({ createdAt: 1 });

        res.json({ success: true, data: comments });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
});

// Post a comment
router.post('/', async (req, res) => {
    try {
        const { taskId, text } = req.body;

        if (!taskId || !text || !text.trim()) {
            return res.status(400).json({ success: false, message: 'Task ID and text are required' });
        }

        const task = await Task.findById(taskId);
        if (!task) {
            return res.status(404).json({ success: false, message: 'Task not found' });
        }

        // Permission check: Freelancers can only comment on their own assigned tasks (or unassigned tasks)
        if (req.user.role !== 'admin' && task.assignedTo && task.assignedTo.toString() !== req.user._id.toString()) {
            return res.status(403).json({ success: false, message: 'You can only post comments on tasks assigned to you.' });
        }

        const Notification = require('../models/Notification');
        const User = require('../models/User');

        const comment = await Comment.create({
            task: taskId,
            project: task.project,
            user: req.user._id,
            text: text.trim()
        });

        const populatedComment = await Comment.findById(comment._id).populate('user', 'name username avatar role');

        await logActivity({
            project: task.project,
            task: task._id,
            user: req.user._id,
            action: 'task_updated',
            details: `Commented on Task #${task.taskNumber || ''} "${task.title}": "${text.trim().substring(0, 50)}${text.length > 50 ? '...' : ''}"`
        });

        // Generate Notification for assigned user or admin
        const notifTitle = `New Comment on Task #${task.taskNumber || ''}`;
        const notifMessage = `${req.user.name}: "${text.trim().substring(0, 60)}${text.length > 60 ? '...' : ''}"`;

        if (req.user.role === 'admin') {
            if (task.assignedTo && task.assignedTo.toString() !== req.user._id.toString()) {
                await Notification.create({
                    recipient: task.assignedTo,
                    sender: req.user._id,
                    project: task.project,
                    task: task._id,
                    title: notifTitle,
                    message: notifMessage,
                    type: 'comment'
                });
            }
        } else {
            const adminUsers = await User.find({ role: 'admin' });
            for (const admin of adminUsers) {
                if (admin._id.toString() !== req.user._id.toString()) {
                    await Notification.create({
                        recipient: admin._id,
                        sender: req.user._id,
                        project: task.project,
                        task: task._id,
                        title: notifTitle,
                        message: notifMessage,
                        type: 'comment'
                    });
                }
            }
        }

        res.status(201).json({ success: true, data: populatedComment });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
});

// Delete a comment
router.delete('/:id', async (req, res) => {
    try {
        const comment = await Comment.findById(req.params.id);
        if (!comment) {
            return res.status(404).json({ success: false, message: 'Comment not found' });
        }

        if (req.user.role !== 'admin' && comment.user.toString() !== req.user._id.toString()) {
            return res.status(403).json({ success: false, message: 'Not authorized to delete this comment' });
        }

        // Clean up notifications generated by this comment/task
        const Notification = require('../models/Notification');
        await Notification.deleteMany({
            task: comment.task,
            type: 'comment',
            sender: comment.user
        });

        await Comment.findByIdAndDelete(req.params.id);
        res.json({ success: true, message: 'Comment deleted' });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
});

module.exports = router;
